### ISSUE TITLE
Task0 Checklist for Classes

### ISSUE THREAD

**Issue by Nekyi4** [varcrimer/Programming-Technology-Lab#2]
- [x] create a GitHub repository together with your teammate. One repository per development team is expected
- [x] copy the contents of the file GitHubREADMETempllate.md to the file README.md of the repository
- [x] complete the file by entering your personal identification (full name or initials) data and generate GUIDs
- [x] the repository should contain a sample program that can be compiled
- [x] unit tests - that can be executed and passed - should be included in the program
- [x] copy the repository URL (green button) and your GUID into the text of the Feedback comment of the task
